logging:
  file:
    path: logs
  level:
    root: info
    #    com.zaxxer.hikari.HikariConfig: DEBUG
    #    com.zaxxer.hikari: TRACE
    org.hibernate:
      #      SQL: DEBUG
      orm.jdbc.bind: TRACE
  logback:
    rollingpolicy:
      max-history: 7

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: test
    password: 1234
    hikari:
      connection-timeout: 10000
      idleTimeout: 10000
      validation-timeout: 10000
      maxLifetime: 1790000
  jpa:
    # https://stackoverflow.com/questions/37066024/what-is-the-mariadb-dialect-class-name-for-hibernate
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties.hibernate:
      default_batch_fetch_size: 100
      format_sql: true
      show_sql: true
    hibernate:
      ddl-auto: create-drop

  messages:
    basename: i18n/exception
    encoding: UTF-8
  output:
    ansi:
      enabled: always
  jwt:
    secret: VyAHb65Ww8V1vj2FXHMS6g==

  servlet:
    multipart:
      maxFileSize: 30MB
      maxRequestSize: 50MB
  config:
    import: optional:file:.env[.properties]

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    default-model-expand-depth: 99

web:
  encrypt:
    key: Uyn+GjQZ1to6HCyxxnCv7yyY8OGI9uhTiVkWEPAqOz4=
  mail:
    changePwURL: https://dev-cms.seobuk.kr/#/confirm-password
    smtp:
      host: smtp.gmail.com
      port: 587
      user: gsdgdg
      pass: gdsg
      mail: noreply@cyvietnam.com
